"""
Options_Postscript.py

This file is automatically generated/modified when Options are configured.
If this file is corrupted/deleted, it will be re-created next time Options are configured.
So use the Options dialog instead of messing around in here :D

Format: [ initialValue, typeCode, stringPrompt, helpString ] 
See OptionDialog.py in UserInterface for typeCodes. 

Last modified on Mon Mar 15 18:38:11 2010 by Unamed
"""

def getOptionDictionary():

  optionDictionary = dict()

  optionDictionary['Color mode'] = ['color', [8, 'color', 'grey', 'mono'], 'Export color mode', '']
  optionDictionary['Rotation'] = ['portrait', [8, 'portrait', 'landscape'], 'Export rotation', '']
  optionDictionary['Mask color'] = ['red', [5, 'Choose color'], 'Boundary mask color', '']
  optionDictionary['Mask transparency'] = [True, [0], 'Transparent boundary mask', '']
  optionDictionary['L0'] = [None, [9, 'times 12', 'blue', 'left'], '', '']
  optionDictionary['L1'] = [None, [9, 'times 12', 'blue', 'left'], 'After pressing OK, you must select the canvas area to export as postscript', '']
  optionDictionary['L2'] = [None, [9, 'times 12', 'blue', 'left'], 'You can modify boundaries by left-clicking and moving the mouse around', '']
  optionDictionary['L3'] = [None, [9, 'times 12', 'blue', 'left'], 'Right-clicking will set the new boundary position', '']
  optionDictionary['L4'] = [None, [9, 'times 12', 'blue', 'left'], 'Right-clicking again will do the actual postscript export', '']
  optionDictionary['seperator1'] = ['', [11], '', '']
  optionDictionary['SVG export mode'] = [True, [0], 'Export to SVG instead of postscript', '']
  optionDictionary['L5'] = [None, [9, 'times 12', 'blue', 'left'], 'NOTE: SVG exports selected items only (if no selection then entire canvas)', '']
  return optionDictionary
